# Generated by Django 4.2.7 on 2023-11-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_photo",
            field=models.ImageField(default="default.jpg", upload_to="id_photos/"),
        ),
    ]
