# Generated by Django 4.2.7 on 2023-11-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profile_id_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
